### ISSUE TITLE
Does / should FID duration reflect time to next render frame?

### ISSUE THREAD

**Issue by igrigorik** [WICG/event-timing#25]
Reading through the spec, confused by stated goals vs. processing (perhaps related to https://github.com/WICG/event-timing/issues/6)..

> Finally, this specification allows developers to obtain detailed information about the timing of the rendering that occurs right after the event has been processed. This can be useful to measure the overhead of website modifications that are triggered by events. - [introduction](https://wicg.github.io/event-timing/#sec-intro)
> 
> The duration attribute’s getter must return the difference between the time of the first update the rendering occurring after associated event has been dispatched and the startTime, rounded up to the nearest 8 ms. - [PerformanceEventTiming](https://wicg.github.io/event-timing/#performanceeventtiming)
> 
> If timingEntry’s duration attribute value is greater than 56 AND if timingEntry’s processingStart attribute value is not equal to timingEntry’s processingEnd attribute value, then queue the entry timingEntry on window. — [dispatch pending entries](https://wicg.github.io/event-timing/#sec-dispatch-pending)

In the intro and in the attribute definition we seem to motivate the use case of event's startTime and all the way to rendering timestamp after all the event process has finished. However, in processing we talk about 56ms and some of our other comms indicate that we, in fact, exclude event processing time. Which of these is true? Or, am I misreading the intent here?

---

> Excluding input handling makes FID easier to reason about. If we included handling time, then what the user interacts with matters, which introduces a bunch of complexity. In practice, the delay is the vast majority of the problem. It's true that including response time would make this slightly more user facing, but I don't think it's worth it.

@tdresser I'm confused by the above, isn't the whole point of RUM event timing to capture the end-to-end user visible delays, which means including the processing time?

/cc @philipwalton @yoavweiss

**Comment by tdresser** [comment]
We can't reliably capture end-to-end latency for events handled by JS. If we try, by looking at the time to produce the next frame, we incentivize postponing handling of input to the next frame, which is bad for users.

Event timing exposes time to next frame as well as the queueing time, as it is a useful signal, but for FID we only use the queueing time. The web perf API for first input does expose the time until next frame as well, but it isn't as generally useful.

Long term we plan to support events with custom end times, potentially via an event.waitUntil approach, similar to waitUntil in service workers.

**Comment by npm1** [comment]
The short answer to the title of this issue is no. We do want to eventually capture the full end-to-end user visible experience. But using the next frame is not good enough. The developer may have posted tasks to execute most of the work async. And that means that there is no guarantee that all of this work will be visible during the next frame. Hence why we choose to focus on something that is guaranteed to be a part of the delay, regardless of how you code: from hardware timestamp to processing start.

Why not include processing end here? Because then the delay would be very skewed depending on whether you do a lot of work sync or choose to do it async. And we should not penalize the sync work in this case: it's work related to the user input! In case you do want to measure this, because your coding practices make it so that these values make sense, we do provide the processing end and the next frame time. But as a 'metric good for comparing all websites', FID excludes event processing time.

Any thoughts on how to make this clearer in the explainer/spec?

**Comment by igrigorik** [comment]
Async processing: ack, that's a gnarly one. 

> Event timing exposes time to next frame as well as the queueing time, as it is a useful signal, but for FID we only use the queueing time. The web perf API for first input does expose the time until next frame as well, but it isn't as generally useful.

@tdresser I'm a little confused, to confirm.. You're saying, both `firstInput` and `event` entry types should report duration as time to next frame? 

@npm1 thanks, understand the current reasoning, but tbh still not entirely convinced of the conclusion. Maybe you can talk me out of it..

---

The meta goal is for a site to "complete a transition initiated by user input within 100ms" — [RAIL](https://developers.google.com/web/fundamentals/performance/rail#response)

In the lab, given that we don't know the exact sequence of interactions, code execution, etc., the guidance to developers is to ensure that there are no long tasks that can block processing, the event processing itself does not occupy a lot of time, etc. As a result, for everything to complete we ask developers to keep their event processing under 50ms.

On the other hand, In the field (FID) we are measuring what the user actually experienced, and we know how long the queuing time, processing time, and other work took between frames. As a result, if the goal is to ensure that application responds to the user in <100ms, then field data can and should answer that precisely, or as precisely as it can. Saying that an event took >50ms queuing does not actually tell me if that resulted in >100ms response. Granted, yes, due to async processing we can't guarantee that next frame rendered visual response to the user in the next logical frame. However, even then, that offers an improved and more accurate floor signal against the stated goal? Stated differently, thresholding FID on >50ms queuing time only will surface false positives, and thresholding FID on >100ms time to next frame eliminates false positives but does not strictly guarantee that visual response is rendered.. but that's a true in both cases due to async processing.

To layer on the above, I'm approaching this from a policy perspective. Imagine one wants to introduce a policy (Feature Policy or some 3P enforced policy), whose goal is to best approximate <100ms response to the user. Using the 50ms queueing time will unfairly penalize cases (and remaining 50ms is half the entire budget!) where the site responds within 100ms despite having a 50ms+ queuing delay, whereas measuring the time-to-next frame gives a reliable floor for the policy: this is the *earliest* time when response could have been visible and thus any value over 100ms is a strict violation of the policy.

**Comment by tdresser** [comment]
"both firstInput and event entry types should report duration as time to next frame?"
That's correct. Both expose duration as time to next frame, but also expose the queuing delay.

I think we're conflating the web perf API and our recommended usage of the API here. The API exposes all of this data. Chrome intends to recommend that folks look at the queuing time of their first input as a particularly valuable signal.

This conversation seems to be about whether Chrome should recommend queuing time of first input as a particularly valuable signal. There's a trade-off here between accuracy, and incentivizing the right behavior.

It's true that using the time to next frame is more accurate than just the queuing time. However, it incentivizes developers to process input asynchronously, which is bad for users.

We'd rather capture less of the pipeline and incentivize the right behavior than capture the whole pipeline and incentivize the wrong behavior.

A feature policy trying to approximate < 100ms response using the approach you describe above will suffer the same problem - it encourages making event handling async without good reason.

**Comment by npm1** [comment]
Yea I think that most of this discussion does not belong in this GitHub, it is a Chrome-specific discussion around its FID concept. In EventTiming API we aim to always expose timing for the first input.

One thought from this discussion is that maybe the threshold for EventTiming should be updated to something like 96 instead of 56 because that aligns closer to the guidelline (the duration attribute used for the threshold does include from event timestamp to next frame).

**Comment by npm1** [comment]
@igrigorik just to clarify, the threshold used by EventTiming is based on the `duration` attribute, which includes from hardware timestamp to rendering time. In other words, while FID is defined as the queueing time, the Event Timing API exposes precisely the events you are suggesting (those for which time-to-next-paint exceeds the desired 100ms). This, modulo the change in threshold from 56 to ~100 which I suggested in my comment above.

Next is the question about how to reason about FID specifically... The dela (queueing time) is considered a metric more reliable as a way to compare ALL websites due to async vs sync processing. But I get your point that it's not clear what the guidance here should be. Aiming for 50ms FID may be inadequate because, for example, the actual time-to-user-visible-response could be below 100 even for a FID of 80ms. The spec does not currently have any such guidance yet.

**Comment by igrigorik** [comment]
Thanks guys, this addressed my confusion. To summarize, PerformanceEventTiming:

- `startTime` is the hardware timestamp of the event
- `processingStart` is the queuing time of the event
- `processingEnd` is the timestamp when all events finished
- `duration` is the time of next rendering step, minus `startTime`

Per https://github.com/WICG/event-timing/commit/0f98672fbb7e3d19eb4af7dab1beec18e8146cc0, https://github.com/WICG/event-timing/commit/9b6bc1cc3ecd16e9b8352d0b8056b45206893c54 (@npm1 thanks for making the updates), we will queue these events whenever duration >= 104ms. Except, if it's first input, we'll report the event regardless of duration. 

Last but not least, yes, agree that the specific guidance on how to interpret and what to aim for, for the above attributes is product and tool specific — e.g. Chrome may choose to focus developers attention on queueing time and make recommendations on what that ought to be (<50ms).

Think we're all on the same page? Thanks!

**Comment by npm1** [comment]
Sounds reasonable to me! I've also changed from ceil to round, so that we now report events whenever duration >= 100 ms, which is what we truly want.
