### ISSUE TITLE
Consider recording event timing outside of event dispatch

### ISSUE THREAD

**Issue by tdresser** [WICG/event-timing#8]
We currently record event timing information with event dispatch logic. This deviates from how implementations will behave, as event dispatch is generally short circuited if no listeners exist.

We should consider whether we can spec this in a way that aligns more closely with implementations, but this likely depends on specifying the OS actions which lead to dispatching events, so we shouldn't block on this.

See [here](https://github.com/whatwg/dom/issues/654#issuecomment-395305223) for context.

**Comment by npm1** [comment]
We have the section https://wicg.github.io/event-timing/#sec-queue-other for these cases. It is meant to highlight the fact that a user agent is allowed to report these events but not forced to as it may be impossible or undesirable to do so.

I'm not sure we should rely on OS actions, since event handlers would not have a 1-1 mapping to these. Are these OS actions specified anywhere? If they are not, I would claim this is outside of the scope of EventTiming and should be done by the Event APIs.

Can we consider this closed?
