### ISSUE TITLE
Clarify arbitrary constants in the spec

### ISSUE THREAD

**Issue by fred-wang** [WICG/event-timing#86]
For example:
* rounded to the nearest 8ms (and  in other places)
* or 104 otherwise.
* set minDuration to 16 ; If timingEntry’s duration attribute value is greater than or equal to 16

I see the choice of the two first are explained in the security section and 16 is a multiple of 8 too, but I think a short note explaining these values or referring to the security section would help.

Maybe also worth introducing new constant definitions in the spec with explicit names, so you can reuse them more easily, and so can implementers ? For example:

8 = timeAccuracyConstant
104 = defaultMinDuration = timeAccuracyConstant * ceiling(100ms / timeAccuracyConstant)
16 == 2 * timeAccuracyConstant

**Comment by npm1** [comment]
Thanks, you're right that we could define them and reuse them. I'm not sure that would improve clarity but if that's helpful I can do it. More important is noting the reasoning when they appear in the spec, so people understand where it's coming from. The only one without explanation is 16, and the reasoning for that one is not as interesting. We chose 16 since it would be useful for developers that care about responding in 120 fps to the input. I wouldn't be opposed to considering a different value for the minimum.

**Comment by npm1** [comment]
Sorry for getting back to this so late. I am not aware of precedent with using variables for constants in specs, so I will avoid using that for now. I will add a clarification about the choice of 16
