### ISSUE TITLE
CFC: adopt to WebPerfWG as a Working Draft

### ISSUE THREAD

**Issue by yoavweiss** [WICG/event-timing#94]
The proposal was throughly discussed in the WebPerfWG's calls and meetings, and I believe it is in good shape to be adopted as a Working Draft.
Please vote using :+1:, :-1: or comment.

**Comment by marcoscaceres** [comment]
Although it's great to have 👍 support from WG members, shouldn't the benchmark for adoption be clear multi-implementer interest? Otherwise, we risk adopting things into the WG that might not be implemented by multiple vendors, and might not make sense to have on the REC track.... having said that, if there is already multi-implementer interest, then that's awesome -  it might be good to state that at the top of the CFC.

**Comment by cwilso** [comment]
Garnering that interest is the WebPerf WG's remit, prior to bringing it to CR to prove implementation experience.  It's not a bar for moving INTO the WG, though, especially when there is clear multi-vendor interest.

**Comment by yoavweiss** [comment]
That's not a criteria we have in our [charter](https://www.w3.org/2018/09/webperf/) for adopting proposals. Instead, we have a criteria for multiple interoperable implementations for a spec to make it to PR. 

At the same time, this is a call for **consensus**. If any of the WG members (including implementers) objects to this draft's adoption by the WG, we will deliberate to reach consensus on this, and worst case, resort to a vote.

**Comment by yoavweiss** [comment]
Closing as I'm sending a new CfC, and it'd be better to have a new clean-slate issue.
